[project]
authors = ["Diane Adjavon <adjavond@hhmi.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "flyid"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.13"

[pypi-dependencies]
torch = { version = "==2.5.1+cu124", index = "https://download.pytorch.org/whl/cu124" }
torchvision = { version = "==0.20.1+cu124", index = "https://download.pytorch.org/whl/cu124" }
quac = { path = "/groups/funke/home/adjavond/workspace/projects/QuAC/quac", editable = true }
# quac = { git = "https://github.com/funkelab/quac.git" }
pandas = ">=2.2.3, <3"
wandb = ">=0.19.4, <0.20"
typer = ">=0.15.1, <0.16"
seaborn = ">=0.13.2, <0.14"
matplotlib = ">=3.10.0, <4"
cmap = ">=0.5.0, <0.6"
ipykernel = ">=6.29.5, <7"
