[project]
authors = ["Diane Adjavon <adjavond@hhmi.org>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "bbbc021"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.10"
tqdm = ">=4.67.1,<5"
scikit-learn = ">=1.6.1,<2"
pandas = ">=2.2.3,<3"
numpy = ">=2.2.5,<3"

[pypi-dependencies]
pandas = "*"
ipykernel = "*"
pillow = ">=11.1.0, <12"
tifffile = ">=2025.3.13, <2026"
matplotlib = ">=3.10.1, <4"
scikit-image = "*"
torch = ">=2.7.0, <3"
torchvision = ">=0.22.0, <0.23"
quac = { git = "https://github.com/funkelab/quac", branch = "dev" }
timm = ">=1.0.15, <2"
wandb = ">=0.19.10, <0.20"
accelerate = ">=1.6.0, <2"
seaborn = ">=0.13.2, <0.14"
evaluate = ">=0.4.3, <0.5"
