project: "kidney-classification"
notes: "Resnet18 8 class, with the All 3D data, where we treat z as a channel dimension."
tags: ["kidney", "quac", "resnet18", "classification", "noise_augment_small", "translations", "8 class", "All 3D", "model_ema", "all_samples"]
data:
  data_path: "/nrs/funke/adjavond/data/kidney_cortex_cells/All_8class/All_3D"
  batch_size: 64
model:
  type: "resnet18"
  image_size: 32
  num_classes: 8
  input_fmaps: 7
training:
  epochs: 100
  learning_rate: 0.0001
  checkpoint_dir: "/nrs/funke/adjavond/projects/quac/kidney-classification/resnet18_all_samples"
  device: "cuda"
