project: "kidney-classification"
notes: "Resnet18 model for kidney cortex cells classification. This time with an 8-class problem, added metrics, and added augmentations."
tags: ["kidney", "quac", "resnet18", "classification", "noise_augment", "translations", "8 class"]
data:
  data_path: "/nrs/funke/adjavond/data/kidney_cortex_cells/F33_8class/Mask_2D_Maximum"
  batch_size: 64
val_data:
  data_path: "/nrs/funke/adjavond/data/kidney_cortex_cells/F44_8class/Mask_2D_Maximum"
  batch_size: 64
  augment: False
  balance: False
model:
  type: "resnet18"
  image_size: 32
  num_classes: 8
training:
  epochs: 100
  learning_rate: 0.0001
  checkpoint_dir: "/nrs/funke/adjavond/projects/quac/kidney-classification/resnet18_v1"
  device: "cuda"
