project: "kidney-classification"
notes: "ResNet18 model for kidney cortex cells classification"
tags: ["kidney", "quac", "resnet18", "classification"]
data:
  data_path: "/nrs/funke/adjavond/data/kidney_cortex_cells/F33/Mask_2D_Maximum"
  batch_size: 64
val_data:
  data_path: "/nrs/funke/adjavond/data/kidney_cortex_cells/F44/Mask_2D_Maximum"
  batch_size: 64
  augment: False
  balance: False
model:
  type: "resnet18"
  image_size: 32
  num_classes: 12
training:
  epochs: 100
  learning_rate: 0.0001
  checkpoint_dir: "/nrs/funke/adjavond/projects/quac/kidney-classification/resnet18"
  device: "cuda"
