log:
  project: "fictus-stargan"
  name: "stargan_20241014"
  notes: "Stargan training on fictus dataset"
  tags: 
    - fictus
    - stargan
    - training
    - quac

data: 
  source: "/nrs/funke/adjavond/data/fictus/aggregatum/train"
  reference: "/nrs/funke/adjavond/data/fictus/aggregatum/train"
  img_size: 128
  batch_size: 16
  num_workers: 12
  mean: 0.5 # Default
  std: 0.5  # Default

validation_data: 
  source: "/nrs/funke/adjavond/data/fictus/aggregatum/val"
  reference: "/nrs/funke/adjavond/data/fictus/aggregatum/val"
  img_size: 128
  batch_size: 16
  num_workers: 12
  mean: 0.5  # Default
  std: 0.5  # Default

test_data: 
  source: "/nrs/funke/adjavond/data/fictus/aggregatum/test_small"
  reference: "/nrs/funke/adjavond/data/fictus/aggregatum/test_small"
  img_size: 128
  batch_size: 16
  num_workers: 12
  mean: 0.5  # Default
  std: 0.5  # Default

model: 
  img_size: 128
  style_dim: 64
  latent_dim: 10
  num_domains: 5 
  input_dim: 3
  final_activation: "tanh"  # Note, this is default

loss:
  lambda_ds: 0.5
  lambda_sty: 1.  # Default
  lambda_cyc: 1.  # Default
  lambda_id: 1.  # Default
  ds_iter: 100000 # Default, does not reach 0 in this run, which only goes for 10000

solver:
  root_dir: "/nrs/funke/adjavond/projects/quac/fictus/stargan_20241014"

validation_config: 
  classifier_checkpoint: "/nrs/funke/adjavond/projects/quac/fictus/classification_20241013/best_model.pt"
  mean: null 
  std: null
  assume_normalized: true
  do_nothing: true # Pass the image directly to the classifier

run: 
  log_every: 100
  resume_iter: 0
  total_iters: 10000
  save_every: 1000
  eval_every: 1000